services:
  - type: web
    name: dev-interview-platform-25
    runtime: docker
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dev-interview-db-25
          property: connectionString
      - key: PORT
        value: 8080

databases:
  - name: dev-interview-db-25
    plan: free
    region: oregon
    postgresMajorVersion: 16
